name: graf
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pip:
      - -r requirements/base.txt
      - -r requirements/gpu.txt
      - pytest-cov
      - pre-commit
      - ruff
      - mypy
