"""Regenerate requirements/lock.txt from the current environment.

Walks the transitive closure of the direct dependencies declared in
requirements/base.txt and requirements/dev.txt, pins each package to
the version installed here, and writes requirements/lock.txt.

Run:  python scripts/freeze_lock.py
"""

from __future__ import annotations

import re
import subprocess
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
REQUIREMENTS = REPO / "requirements"


def canonicalize(name: str) -> str:
    return name.lower().replace("_", "-").replace(".", "-")


def parse_requirements(path: Path) -> list[str]:
    """Direct package names from a requirements file. Skips -r includes
    and comments."""
    out: list[str] = []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or line.startswith("-"):
            continue
        # strip version specifiers
        name = re.split(r"[<>=!~\[]", line, maxsplit=1)[0].strip()
        if name:
            out.append(name)
    return out


def walk_closure(roots: list[str]) -> set[str]:
    seen: set[str] = set()
    queue = [canonicalize(r) for r in roots]
    while queue:
        key = queue.pop()
        if key in seen:
            continue
        seen.add(key)
        try:
            dist = distribution(key)
        except PackageNotFoundError:
            continue
        for req in dist.requires or []:
            if ";" in req:
                marker = req.split(";", 1)[1].lower()
                # Skip extras and non-Linux platform markers; the lock is
                # generated on Linux and should not pin deps that are
                # only needed on Windows or macOS.
                if "extra" in marker:
                    continue
                if "sys_platform" in marker and "linux" not in marker:
                    continue
                if "platform_system" in marker and "linux" not in marker:
                    continue
            base = req.split(";")[0].strip()
            # Split on the first version/extras specifier character, not
            # on whitespace: `pluggy<2,>=1.5` has no space.
            dep = re.split(r"[<>=!~\[]", base, maxsplit=1)[0].strip()
            dep_key = canonicalize(dep)
            if dep_key and dep_key not in seen:
                queue.append(dep_key)
    return seen


def main() -> int:
    r = subprocess.run(["pip", "freeze"], capture_output=True, text=True)
    frozen: dict[str, tuple[str, str]] = {}
    for line in r.stdout.splitlines():
        if "==" in line:
            n, v = line.split("==", 1)
            frozen[canonicalize(n)] = (n, v)

    roots = parse_requirements(REQUIREMENTS / "base.txt") + parse_requirements(
        REQUIREMENTS / "dev.txt"
    )
    closure = walk_closure(roots)

    exclude = {"pip", "setuptools", "wheel", "pkg-resources", "pkg_resources"}
    pinned = [
        f"{frozen[k][0]}=={frozen[k][1]}"
        for k in sorted(closure)
        if k in frozen and k not in exclude
    ]

    header = [
        "# Fully-pinned dependency closure of base.txt + dev.txt.",
        "#",
        "# Generated by scripts/freeze_lock.py. Regenerate with:",
        "#     python scripts/freeze_lock.py",
        "#",
        "# Scope: base + dev. The gpu extra (torch, torch-geometric) is NOT locked —",
        "# those wheels are hardware- and CUDA-specific and are installed by the",
        "# install instructions in README.md, not from this file.",
        "#",
        "# CI does not use this file: it installs from requirements/{base,dev}.txt",
        "# to test against fresh resolvable versions. This file is for reproducing",
        "# the exact environment a past run used.",
        "",
    ]
    out = REQUIREMENTS / "lock.txt"
    out.write_text("\n".join(header + pinned) + "\n")
    print(f"wrote {out} with {len(pinned)} pinned packages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
